### ISSUE TITLE
[Request] World generator in addittional dimension?

### ISSUE THREAD

**Issue by MSandro** [nicguzzo/skyutils#6]
Hello, would it be possible to use the Skyblock Island World Generator as a dimension, e.g. if you used a different generator when creating the world? I would like to implement a dimension in my modpack using a data pack that uses your generator.

**Comment by nicguzzo** [comment]
I'm not sure, maybe if you can select the world type for the dimension in the data pack, the generator is "skyblock_island".

**Comment by MSandro** [comment]
I already tried, but It seems that the Chunk Generator Name is different.

**Comment by nicguzzo** [comment]
I'm not familliar with the new datapack chunk generation, but maybe inspecting the region files could help finding out what the name should be. On the other hand we could implement this directly in the mod.

**Comment by MSandro** [comment]
[skyutils.json.txt](https://github.com/nicguzzo/skyutils/files/7200634/skyutils.json.txt)
I don't really either. This is my JSON file that is in the "dimension" folder. But it doesn't work ... too bad. I have no idea what I'm doing wrong. I checked your source code, so I know that the chunk generator is registered with the name "skyutils: skyblock_island".

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/134178615-07e1336a-0fb4-47d3-8d0d-6e2d14b141fb.png)
Got it. I forgot to add the dimension_type json...
[skyutils.zip](https://github.com/nicguzzo/skyutils/files/7203404/skyutils.zip)
